<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container9e7O5Mh\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container9e7O5Mh/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container9e7O5Mh.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container9e7O5Mh\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \Container9e7O5Mh\srcApp_KernelDevDebugContainer([
    'container.build_hash' => '9e7O5Mh',
    'container.build_id' => 'f2996400',
    'container.build_time' => 1576503884,
], __DIR__.\DIRECTORY_SEPARATOR.'Container9e7O5Mh');
